=== MOOChub/schema/draft/schemas/course.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://w3id.org/moochub/draft/schemas/course.json",
  "title": "MOOChub v4 learning opportunity",
  "description": "A MOOChub v4 course profile for a learning resource offered by a provider.",
  "type": "object",
  "properties": {
    "@context": {
      "$ref": "https://w3id.org/moochub/draft/schemas/context-schema.json"
    },
    "type": {
      "$ref": "https://w3id.org/moochub/draft/schemas/courseType.json"
    },
    "id": {
      "$ref": "https://w3id.org/moochub/draft/schemas/id.json"
    },
    "url": {
      "$ref": "https://w3id.org/moochub/draft/schemas/url.json"
    },
    "name": {
      "$ref": "https://w3id.org/kim/amb/20231019/schemas/localizedString.json"
    },
    "publisher": {
      "$ref": "https://w3id.org/moochub/draft/schemas/publisher.json"
    },
    "creator": {
      "$ref": "https://w3id.org/moochub/draft/schemas/creator.json"
    },
    "license": {
      "$ref": "https://w3id.org/moochub/draft/schemas/license.json"
    },
    "courseCode": {
      "$ref": "https://w3id.org/moochub/draft/schemas/courseCode.json"
    },
    "abstract": {
      "$ref": "https://w3id.org/kim/amb/20231019/schemas/localizedString.json"
    },
    "description": {
      "$ref": "https://w3id.org/moochub/draft/schemas/richText.json"
    },
    "keywords": {
      "$ref": "https://w3id.org/kim/amb/20231019/schemas/keywords.json"
    },
    "inLanguage": {
      "$ref": "https://w3id.org/kim/amb/20231019/schemas/inLanguage.json"
    },
    "timeRequired": {
      "$ref": "https://w3id.org/moochub/draft/schemas/timeRequired.json"
    },
    "numberOfCredits": {
      "$ref": "https://w3id.org/moochub/draft/schemas/numberOfCredits.json"
    },
    "interactivityType": {
      "$ref": "https://w3id.org/kim/amb/20231019/schemas/interactivityType.json"
    },
    "isAccessibleForFree": {
      "$ref": "https://w3id.org/kim/amb/20231019/schemas/isAccessibleForFree.json"
    },
    "conditionsOfAccess": {
      "$ref": "https://w3id.org/kim/amb/20231019/schemas/conditionsOfAccess.json"
    },
    "accessMode": {
      "$ref": "https://w3id.org/moochub/draft/schemas/accessMode.json"
    },
    "image": {
      "$ref": "https://w3id.org/moochub/draft/schemas/image.json"
    },
    "trailer": {
      "$ref": "https://w3id.org/moochub/draft/schemas/trailer.json"
    },
    "contributor": {
      "$ref": "https://w3id.org/moochub/draft/schemas/contributor.json"
    },
    "funder": {
      "$ref": "https://w3id.org/moochub/draft/schemas/funder.json"
    },
    "audience": {
      "$ref": "https://w3id.org/moochub/draft/schemas/audience.json"
    },
    "coursePrerequisites": {
      "$ref": "https://w3id.org/moochub/draft/schemas/richText.json"
    },
    "prerequisiteCourses": {
      "$ref": "https://w3id.org/moochub/draft/schemas/prerequisiteCourses.json"
    },
    "competencyRequired": {
      "$ref": "https://w3id.org/moochub/draft/schemas/competencyRequired.json"
    },
    "learningOutcomeSummary": {
      "$ref": "https://w3id.org/moochub/draft/schemas/richText.json"
    },
    "teaches": {
      "$ref": "https://w3id.org/moochub/draft/schemas/teaches.json"
    },
    "assesses": {
      "$ref": "https://w3id.org/moochub/draft/schemas/assesses.json"
    },
    "educationalLevel": {
      "$ref": "https://w3id.org/moochub/draft/schemas/educationalLevels.json"
    },
    "educationalAlignment": {
      "$ref": "https://w3id.org/moochub/draft/schemas/educationalAlignment.json"
    },
    "hasCourseInstance": {
      "$ref": "https://w3id.org/moochub/draft/schemas/hasCourseInstance.json"
    },
    "educationalCredentialAwarded": {
      "$ref": "https://w3id.org/moochub/draft/schemas/educationalCredentialAwarded.json"
    },
    "isBasedOn": {
      "$ref": "https://w3id.org/moochub/draft/schemas/isBasedOn.json"
    },
    "isPartOf": {
      "$ref": "https://w3id.org/moochub/draft/schemas/isPartOf.json"
    },
    "hasPart": {
      "$ref": "https://w3id.org/moochub/draft/schemas/hasPart.json"
    },
    "aggregateRating": {
      "$ref": "https://w3id.org/moochub/draft/schemas/aggregateRating.json"
    },
    "dateCreated": {
      "type": "string",
      "format": "date-time"
    },
    "datePublished": {
      "type": "string",
      "format": "date-time"
    },
    "dateModified": {
      "type": "string",
      "format": "date-time"
    },
    "expires": {
      "type": "string",
      "format": "date-time"
    }
  },
  "required": ["id", "type", "name", "publisher", "creator", "license"]
}

=== MOOChub/schema/draft/examples/course/valid/credentialWithParts.json
{
  "@context": [
    "https://w3id.org/moochub/draft/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "id": "urn:uuid:c96a2376-bdf2-4307-a21f-19a4ff141b5f",
  "url": "https://futurelearnlab.de/detailpage.php?id=18",
  "name": {
    "de": "Digital Trainer (Gesamtkurs)"
  },
  "type": ["LearningResource", "Course"],
  "publisher": {
    "id": "https://example.org/organizations/isy",
    "name": {
      "de": "Institut für Interaktive Systeme"
    },
    "type": "Organization"
  },
  "creator": [
    {
      "id": "https://example.org/people/beispielperson",
      "type": "Person",
      "name": "Beispielperson"
    }
  ],
  "license": {
    "type": "License",
    "identifier": "Propriatary"
  },
  "educationalCredentialAwarded": [
    {
      "id": "urn:uuid:1f9d2f1d-2d30-4d18-9e0e-12c004a1cf15",
      "name": {
        "de": "Digital Education Microcredential"
      },
      "type": "EducationalOccupationalCredential",
      "publisher": {
        "id": "https://example.org/organizations/example-university",
        "type": "Organization",
        "name": {
          "de": "Example University"
        }
      },
      "inLanguage": ["de", "en"],
      "numberOfCredits": [
        {
          "type": "CreditPoint",
          "framework": {
            "id": "http://data.europa.eu/snb/education-credit/6fcec5c5af",
            "type": "Concept",
            "prefLabel": {
              "en": "ECTS"
            },
            "inScheme": "http://data.europa.eu/snb/education-credit/25831c2"
          },
          "point": 5
        }
      ],
      "educationalLevel": [
        {
          "id": "https://w3id.org/kim/educationalLevel/level_6",
          "type": "Concept",
          "prefLabel": {
            "en": "Bachelor level"
          },
          "inScheme": "https://w3id.org/kim/educationalLevel/"
        }
      ],
      "educationalAlignment": [
        {
          "type": "AlignmentObject",
          "alignmentType": "educationalSubject",
          "educationalFramework": "ISCED-F",
          "targetName": {
            "en": "Computer use"
          },
          "targetUrl": "http://data.europa.eu/esco/isced-f/0611"
        }
      ],
      "isAwardedBy": [
        {
          "id": "https://provider.example/courses/digital-education",
          "name": {
            "en": "Digital Education Course"
          },
          "type": ["LearningResource", "Course"]
        },
        {
          "id": "https://provider.example/programs/digital-education",
          "name": {
            "en": "Digital Education Program"
          },
          "type": "EducationalOccupationalProgram"
        }
      ],
      "credentialCategory": {
        "id": "http://data.europa.eu/snb/credential/e34929035b",
        "type": "Concept",
        "prefLabel": {
          "de": "Generisch"
        },
        "inScheme": "http://data.europa.eu/snb/credential/25831c2"
      },
      "recognizedBy": [
        {
          "id": "https://example.org/organizations/example-university",
          "type": "Organization",
          "name": {
            "de": "Example University"
          }
        }
      ],
      "hasPart": [
        {
          "id": "https://example.org/credentials/digital-teaching-badge",
          "name": {
            "en": "Digital Teaching Badge"
          },
          "type": "EducationalOccupationalCredential"
        },
        {
          "id": "urn:uuid:c9a1ca5d-e63b-4a34-9d49-1ec0b3c378f2",
          "name": {
            "en": "Learning Design Badge"
          },
          "type": "EducationalOccupationalCredential"
        }
      ],
      "isPartOf": [
        {
          "id": "urn:uuid:7d2e42a8-15f9-4a39-8ac1-79d9b4d20d72",
          "name": {
            "en": "Certificate in Digital Education"
          },
          "type": "EducationalOccupationalCredential"
        }
      ]
    }
  ]
}

=== MOOChub/schema/4.0.0/examples/course/valid/minimalCourse.json
{
  "@context": [
    "https://w3id.org/moochub/4.0.0/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "id": "urn:uuid:c96a2376-bdf2-4307-a21f-19a4ff141b5f",
  "url": "https://futurelearnlab.de/detailpage.php?id=18",
  "name": {
    "de": "Digital Trainer (Gesamtkurs)"
  },
  "type": ["LearningResource", "Course"],
  "publisher": {
    "id": "https://example.org/organizations/isy",
    "name": {
      "de": "Institut für Interaktive Systeme"
    },
    "type": "Organization"
  },
  "creator": [
    {
      "id": "https://example.org/people/beispielperson",
      "type": "Person",
      "name": "Beispielperson"
    }
  ],
  "license": {
    "type": "License",
    "identifier": "Propriatary"
  }
}

=== MOOChub/schema/4.0.0/examples/course/valid/dlcCourse.json
{
  "@context": [
    "https://w3id.org/moochub/4.0.0/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "type": ["LearningResource", "Course"],
  "id": "urn:uuid:2bcef8e3-35f3-4cb6-badd-e2220919bdc9",
  "url": "https://lernen.dlc.sh/course/view.php?id=34",
  "name": {
    "de": "Customer Experience Management"
  },
  "description": [
    {
      "type": "TextObject",
      "inLanguage": "de",
      "text": "\u003Cdiv class='teasertext'\u003E\u003Cp\u003EProdukte und Dienstleistungen werden durch die digitale Transformation zunehmend komplexer. Der Kern des Angebotes wird für Kunden durch die Parallelität von analogen und digitalen Komponenten schwerer greifbar – die Wahrnehmung richtet sich stärker auf das Gesamterlebnis, welches Kunden mit einem Angebot haben. Pine und Gilmore (1998) sprechen daher auch von der „Experience Economy“. Diese ökonomisch relevanten Erlebnisse sollten gesteuert, bzw. gemanaged werden.\u003C/p\u003E\r\n\u003Cp\u003EIn diesem MOOC erfahrt Ihr die Gründe und lernt die Mechanismen, die hinter diesen komplexen Angeboten stecken. Ziel ist es, über dieses Verständnis Wege aufzuzeigen, wie man komplexe Angebote – im Sinne eines Management-Ansatzes – lenken kann.\u003C/p\u003E\u003C/div\u003E\u003Cdiv class='learninggoals'\u003E\u003Ch3\u003ELernziele\u003C/h3\u003E\u003Col\u003E\r\n\u003Cli\u003EDu kannst die Komplexität von Angeboten in der „Experience Economy“ nachvollziehen und diese in einem wirtschaftlichen Kontext einordnen.\u003C/li\u003E\r\n\u003Cli\u003EDu kannst komplexe Angebote in Geschäftsmodelle überführen und deren Potenzial analysieren sowie eine Optimierung verschiedener Geschäftsmodelle vorschlagen.\u003C/li\u003E\r\n\u003Cli\u003EDu verstehst die unterschiedlichen Arten von Innovation und kannst auf deren Basis entscheiden, welche Form der Geschäftsmodellierung sinnvoll ist. Du kannst in einem Innovationsportfolio aus unterschiedlichen Angeboten Geschäftsmodellen entwickeln.\u003C/li\u003E\r\n\u003Cli\u003EDu verstehst die Herausforderungen, die sich für Unternehmen aus der Entwicklung unterschiedlicher und immer wieder neuer Angebote ergeben und kannst einschätzen, welche Veränderungen in der Organisationsstruktur sowie in der Unternehmenskultur notwendig sind, um sowohl das Entwickeln von neuen Angeboten als auch deren Umsetzung innerhalb eines oder mehrerer Geschäftsmodelle umzusetzen\u003C/li\u003E\r\n\u003Cli\u003EDu kennst unterschiedliche operative Ansätze, um innovative Angebote zu entwickeln und diese in Geschäftsmodelle zu überführen. Du bist in der Lage, auf Basis dieser Kenntnisse spezifische Ansätze (Design Thinking, Lean Start-up, etc.) vorzuschlagen und deren Vor- und Nachteile im jeweiligen Anwendungsfall gegeneinander abzuwägen.\u003C/li\u003E\r\n\u003C/ol\u003E\u003C/div\u003E\u003Cdiv class='structure'\u003E\u003Ch3\u003EKursaufbau\u003C/h3\u003E\u003Col\u003E\r\n\u003Cli\u003EGrundlagen des Customer Experience Management und Charakteristika von (digitalen) Angeboten\u003C/li\u003E\r\n\u003Cli\u003EGeschäftsmodelle in der digitalen Ökonomie\u003C/li\u003E\r\n\u003Cli\u003EInnovationsmanagement in der digitalen Welt\u003C/li\u003E\r\n\u003Cli\u003EWandel von Organisationsstrukturen durch dynamische Anforderungen an Customer Experiences\u003C/li\u003E\r\n\u003C/ol\u003E\u003C/div\u003E",
      "encodingFormat": "text/html"
    }
  ],
  "keywords": ["CEM", "Customer Experience Management"],
  "inLanguage": ["de"],
  "timeRequired": "PT45H",
  "isAccessibleForFree": true,
  "hasCourseInstance": [
    {
      "id": "urn:uuid:63dc73a1-3aa3-4f5c-bb96-364d0c25423b",
      "type": "CourseInstance",
      "courseMode": ["online", "asynchronous"],
      "instructor": [
        {
          "id": "urn:uuid:563d8254-bfb4-4769-bfaf-ca6f69c345b4",
          "type": "Person",
          "name": "Prof. Dr. Eric Horster"
        }
      ]
    }
  ],
  "teaches": [
    {
      "type": "Competency",
      "id": "urn:uuid:4364929a-2844-46d0-837f-626f8998fa95",
      "name": {
        "de": "Fähigkeit zur Analyse und Optimierung von Geschäftsmodellen in der Experience Economy"
      },
      "relatedSkill": [
        {
          "type": "Concept",
          "id": "http://data.europa.eu/esco/skill/7bb5d9af-0a7e-48a7-a860-0e1ded0f6e75",
          "inScheme": "http://data.europa.eu/esco/concept-scheme/skills",
          "prefLabel": {
            "de": "Kundenerlebnisse gestalten",
            "en": "design customer experiences"
          }
        },
        {
          "type": "Concept",
          "id": "http://data.europa.eu/esco/skill/d63f49de-cb72-4ce3-9553-a374a4f32f52",
          "inScheme": "http://data.europa.eu/esco/concept-scheme/skills",
          "prefLabel": {
            "de": "Kundendaten analysieren",
            "en": "analyse data about clients"
          }
        }
      ],
      "proficiencyLevel": [
        {
          "type": "Concept",
          "id": "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/DIGCOMP/DIGCOMP3.0/DigComp%203.0%20Data%20Supplement%2024%20Nov%202025.jsonld#ProficiencyLevel/Intermediate_3",
          "inScheme": "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/DIGCOMP/DIGCOMP3.0/DigComp%203.0%20Data%20Supplement%2024%20Nov%202025.jsonld",
          "prefLabel": {
            "en": "Fortgeschritten (Level 3)"
          }
        }
      ]
    }
  ],
  "publisher": {
    "id": "https://dlc.sh",
    "type": "Organization",
    "name": {
      "de": "Digital Learning Campus"
    },
    "sameAs": ["https://dlc.sh"],
    "image": {
      "type": "ImageObject",
      "contentUrl": "https://lernen.dlc.sh/pluginfile.php/1/local_ildmeta/provider/1/logo_dlc.svg",
      "license": {
        "type": "License",
        "identifier": "Proprietary"
      }
    }
  },
  "creator": [
    {
      "id": "urn:uuid:563d8254-bfb4-4769-bfaf-ca6f69c345b4",
      "type": "Person",
      "name": "Prof. Dr. Eric Horster",
      "description": [
        {
          "type": "TextObject",
          "inLanguage": "de",
          "text": "\u003Cp\u003EProf. Dr. Eric Horster ist Professor im Studiengang International Tourism Management an der \u003Ca href=\"http://www.fh-westkueste.de/startseite/fachbereich-wirtschaft/ansprechpartner/professoren/horster/\"\u003EFachhochschule Westküste\u003C/a\u003E in Heide. Seine Arbeits- und Forschungsschwerpunkte sind der Themenkomplex Linked Open Data sowie das Customer Experience Management. Diese Themen setzt er in zahlreichen Projekten auch für die Praxis um.\u003C/p\u003E",
          "encodingFormat": "text/html"
        }
      ],
      "image": {
        "type": "ImageObject",
        "contentUrl": "https://lernen.dlc.sh/pluginfile.php/1820/local_ildmeta/detailslecturer_image_1/0/56398b92ab5f8b49e4f2885924a2f8fc56b4c445.png",
        "license": {
          "type": "License",
          "identifier": "Proprietary"
        }
      }
    }
  ],
  "image": {
    "type": "ImageObject",
    "contentUrl": "https://lernen.dlc.sh/pluginfile.php/1820/course/overviewfiles/c4c7.PNG",
    "license": {
      "type": "License",
      "identifier": "Proprietary"
    }
  },
  "trailer": {
    "type": "VideoObject",
    "contentUrl": "https://www.youtube.com/watch?v=jr7XGpT-71c",
    "license": {
      "type": "License",
      "identifier": "Proprietary"
    }
  },
  "license": {
    "type": "License",
    "identifier": "CC-BY-4.0",
    "id": "https://spdx.org/licenses/CC-BY-4.0.html"
  },
  "expires": "2025-12-02T00:00:00+01:00"
}

=== MOOChub/schema/4.0.0/examples/course/valid/imooxCourse.json
{
  "@context": [
    "https://w3id.org/moochub/4.0.0/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "type": ["LearningResource", "Course"],
  "id": "urn:uuid:bcca20ca-d659-50ec-bbbd-3202cf88aca0",
  "url": "https://imoox.at/course/maker",
  "name": {
    "de": "“Making” - Kreatives digitales Gestalten mit Kindern"
  },
  "description": [
    {
      "type": "TextObject",
      "inLanguage": "de",
      "text": " \"Making\" - der offene Online-Kurs zum kreativen digitalen Gestalten und Experimentieren mit Kindern ist eine siebenwöchige Einführung in unterschiedliche Making-Werkzeuge und -Aktivitäten für Kinder in der Schule und Kinderarbeit. Handlungsorientiert und praxisnah werden ausgewählte Werkzeuge der Making-Bewegung vorgestellt und von Expertinnen konkrete Beispiele für ihren Einsatz gegeben sowie Herausforderungen und Tipps genannt. Geplant sind so die Vorstellung von ausgewählten Unterrichts- oder Workshopszenarien fürs Programmieren, Roboterbauen oder 3D-Drucken. Der Kurs wendet sich dabei explizit an Einsteiger/innen, d.h. Personen, die selbst noch keine Erfahrungen mit den Werkzeugen haben. ",
      "encodingFormat": "text/plain"
    }
  ],
  "inLanguage": ["de"],
  "courseCode": "3",
  "hasCourseInstance": [
    {
      "id": "urn:uuid:c33bf3b6-01f3-4b13-b12d-0292331e2f92",
      "type": "CourseInstance",
      "courseMode": ["online"],
      "startDate": "2015-10-19T12:00:00+02:00",
      "duration": "P7W",
      "instructor": [
        {
          "id": "urn:uuid:e54670a9-3f6c-404d-b3ee-283c5fcf7af5",
          "type": "Person",
          "name": "Martin Ebner"
        },
        {
          "id": "urn:uuid:baf292f8-998b-4591-948f-1b75386c29ec",
          "type": "Person",
          "name": "Sandra Schön"
        }
      ],
      "offers": [
        {
          "type": "Offer",
          "price": 0,
          "priceCurrency": "EUR",
          "paymentFrequency": "one-time",
          "category": "complete"
        }
      ]
    }
  ],
  "image": {
    "type": "ImageObject",
    "contentUrl": "https://imoox.at/mooc/pluginfile.php/15775/course/overviewfiles/Making.jpg",
    "license": {
      "type": "License",
      "id": "https://creativecommons.org/publicdomain/zero/1.0/",
      "identifier": "CC0-1.0"
    }
  },
  "contributor": [
    {
      "id": "urn:uuid:a61cb574-8b70-49f1-b4e9-be2b31624075",
      "type": "Organization",
      "name": {
        "de": "Technische Universität Graz"
      }
    }
  ],
  "publisher": {
    "id": "https://imoox.at/mooc",
    "type": "Organization",
    "name": {
      "de": "iMooX"
    },
    "sameAs": ["https://imoox.at/mooc"]
  },
  "timeRequired": "PT14H",
  "license": {
    "type": "License",
    "id": "https://creativecommons.org/licenses/by-sa/4.0/",
    "identifier": "CC-BY-SA-4.0"
  },
  "isAccessibleForFree": true,
  "educationalAlignment": [
    {
      "type": "AlignmentObject",
      "alignmentType": "educationalSubject",
      "educationalFramework": "OEFOS",
      "targetName": {
        "en": "Computer Sciences",
        "de": "Informatik"
      },
      "identifier": "102"
    },
    {
      "type": "AlignmentObject",
      "alignmentType": "educationalSubject",
      "educationalFramework": "OEFOS",
      "targetName": {
        "en": "Physics",
        "de": "Physik"
      },
      "identifier": "103"
    }
  ],
  "creator": [
    {
      "id": "urn:uuid:e54670a9-3f6c-404d-b3ee-283c5fcf7af5",
      "type": "Person",
      "name": "Martin Ebner"
    },
    {
      "id": "urn:uuid:baf292f8-998b-4591-948f-1b75386c29ec",
      "type": "Person",
      "name": "Sandra Schön"
    }
  ]
}

=== MOOChub/schema/draft/examples/course/valid/orcanrw.json
{
  "@context": [
    "https://w3id.org/moochub/draft/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "type": ["LearningResource", "Course"],
  "id": "urn:uuid:183595bb-1325-4083-8236-a98fbf4c4fe3",
  "url": "https://www.orca.nrw/starker-start-ins-studium/fuer-studierende/mathematik/wintcheck/",
  "name": {
    "de": "WINT-Check Mathematik"
  },
  "description": [
    {
      "type": "TextObject",
      "inLanguage": "de",
      "text": "Machen Sie sich vertraut mit den mathematischen Anforderungen in WINT-Studiengängen und überprüfen Sie Ihre Vorkenntnisse. Eine ausführliche Übersicht über die 13 Wissensbereiche samt Themenfeldern bekommen Sie im WINT-Katalog Mathematik, auf den sich die Universitäten und Hochschulen für angewandte Wissenschaften in Nordrhein-Westfalen geeinigt haben. Als weitere Orientierung bietet die Veröffentlichung SINUS.NRW eine Sammlung von Aufgaben, die ohne Nutzung von technischen Hilfsmitteln bei Aufnahme eines Studiums mit Mathematikanteil gelöst werden können sollen.",
      "encodingFormat": "text/plain"
    }
  ],
  "inLanguage": ["de"],
  "keywords": [
    "Mathematik",
    "WINT-Fächer",
    "Selbsteinschätzung",
    "Studienanforderungen",
    "Studienbeginn"
  ],
  "isAccessibleForFree": true,
  "publisher": {
    "id": "https://www.orca.nrw",
    "type": "Organization",
    "name": {
      "de": "Geschäftsstelle des Landesportals ORCA.nrw"
    },
    "sameAs": ["https://www.orca.nrw"],
    "description": [
      {
        "type": "TextObject",
        "inLanguage": "de",
        "text": "ORCA.nrw - das Landesportal für Studium und Lehre in Nordrhein-Westfalen",
        "encodingFormat": "text/plain"
      }
    ]
  },
  "creator": [
    {
      "id": "urn:uuid:88f4831d-ad55-48e8-b3a1-28c5d1654195",
      "type": "Person",
      "name": "Johanna Heitzer",
      "honorificPrefix": "Prof."
    },
    {
      "id": "urn:uuid:0ac1f284-e498-4a58-8a12-15ba0000c17e",
      "type": "Person",
      "name": "Fani Lauermann",
      "honorificPrefix": "Prof.",
      "sameAs": ["https://orcid.org/0000-0002-2051-1006"]
    }
  ],
  "license": {
    "type": "License",
    "identifier": "CC-BY-SA-4.0",
    "id": "https://creativecommons.org/licenses/by-sa/4.0/"
  },
  "image": {
    "type": "ImageObject",
    "contentUrl": "https://www.orca.nrw/wp-content/uploads/2025/07/WINT-Check_Mathematik-ORCA.png",
    "license": {
      "type": "License",
      "id": "https://creativecommons.org/licenses/by-sa/4.0/",
      "identifier": "CC-BY-SA-4.0"
    }
  },
  "trailer": {
    "contentUrl": "https://www.orca.nrw/wp-content/uploads/2024/07/fcd42339-939e-4003-980b-727cfffb0880.mp4",
    "type": "VideoObject",
    "license": {
      "type": "License",
      "id": "https://creativecommons.org/licenses/by-sa/4.0/",
      "identifier": "CC-BY-SA-4.0"
    }
  }
}

=== MOOChub/schema/4.0.0/examples/course/valid/courseWithMinimalCredential.json
{
  "@context": [
    "https://w3id.org/moochub/4.0.0/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "id": "urn:uuid:c96a2376-bdf2-4307-a21f-19a4ff141b5f",
  "url": "https://futurelearnlab.de/detailpage.php?id=18",
  "name": {
    "de": "Digital Trainer (Gesamtkurs)"
  },
  "type": ["LearningResource", "Course"],
  "publisher": {
    "id": "https://example.org/organizations/isy",
    "name": {
      "de": "Institut für Interaktive Systeme"
    },
    "type": "Organization"
  },
  "creator": [
    {
      "id": "https://example.org/people/beispielperson",
      "type": "Person",
      "name": "Beispielperson"
    }
  ],
  "license": {
    "type": "License",
    "identifier": "Propriatary"
  },
  "educationalCredentialAwarded": [
    {
      "id": "https://example.org/credentials/digital-teaching-badge",
      "name": {
        "de": "Digital Teaching Badge"
      },
      "type": "EducationalOccupationalCredential",
      "competencyRequired": [
        {
          "id": "https://example.org/competencies/digital-teaching",
          "type": "Competency",
          "name": {
            "en": "Digital teaching"
          }
        }
      ],
      "educationalLevel": [
        {
          "id": "https://w3id.org/kim/educationalLevel/level_6",
          "type": "Concept",
          "prefLabel": {
            "de": "Bachelor oder äquivalent",
            "en": "Bachelor or equivalent"
          }
        }
      ],
      "credentialCategory": {
        "id": "http://data.europa.eu/snb/credential/e34929035b",
        "type": "Concept",
        "inScheme": "http://data.europa.eu/snb/credential/25831c2"
      },
      "recognizedBy": [
        {
          "id": "https://example.org/organizations/example-academy",
          "type": "Organization",
          "name": {
            "de": "Example Academy"
          }
        }
      ],
      "description": [
        {
          "type": "TextObject",
          "inLanguage": "de",
          "text": "Dieses Badge bescheinigt die erfolgreiche Teilnahme am Kurs Digital Trainer (Gesamtkurs).",
          "encodingFormat": "text/plain"
        }
      ],
      "url": "https://example.org/credentials/digital-teaching-badge",
      "image": {
        "type": "ImageObject",
        "contentUrl": "https://example.org/images/digital-teaching-badge.png",
        "license": {
          "type": "License",
          "id": "https://creativecommons.org/licenses/by/4.0/",
          "identifier": "CC BY 4.0"
        }
      }
    }
  ]
}

=== MOOChub/schema/draft/examples/course/valid/openvhbCourse.json
{
  "@context": [
    "https://w3id.org/moochub/draft/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "type": ["LearningResource", "Course"],
  "id": "urn:uuid:c5e871f6-58b0-45bb-9c15-b0bdb890a6c4",
  "url": "https://open.vhb.org/blocks/occoursemetaselect/detailpage.php?id=44",
  "name": {
    "de": "Medienrecht für Journalisten und Blogger"
  },
  "description": [
    {
      "type": "TextObject",
      "inLanguage": "de",
      "text": "\r\nDass das Internet kein rechtsfreier Raum ist, soll nicht davor verschrecken, die Online-Möglichkeiten der Kommunikation und Verbreitung von Inhalten aktiv zu nutzen. Doch für das Bloggen und für die Inhalte-Verbreitung gibt es Vorgaben, die man kennen muss. Der Kurs „Medienrecht für Journalisten und Blogger“ möchte weniger das große Mediensystem erklären als die alltäglichen Fragen beantworten. Hierfür ist der schon länger existierende und bewährte CLASSIC vhb-Kurs „Konvergentes Medienrecht“ um seine theoretischen Teile gekürzt, auf die praktische Perspektive des Einzelnen fokussiert und um interaktive und multimediale Elemente ergänzt worden.\r\nDer Kurs soll und kann seiner Leserschaft Ängste und Sorgen vor rechtlichen Stolpersteinen nehmen. \r\n",
      "encodingFormat": "text/plain"
    }
  ],
  "inLanguage": ["de"],
  "hasCourseInstance": [
    {
      "id": "urn:uuid:2df09c03-0718-4482-bfd3-8899899a1099",
      "type": "CourseInstance",
      "startDate": "2019-07-08T22:00:00+00:00",
      "instructor": [
        {
          "id": "urn:uuid:7b8c11b9-3f4c-4a91-8382-2b7c9e687ee6",
          "type": "Person",
          "name": "Kai von Lewinski",
          "honorificPrefix": "Prof. Dr. "
        },
        {
          "id": "urn:uuid:f8613d01-675b-4f8b-8c5c-b20258fc14c7",
          "type": "Person",
          "name": "Christoph Neuberger (LMU)",
          "honorificPrefix": "Prof. Dr. "
        }
      ]
    }
  ],
  "image": {
    "type": "ImageObject",
    "contentUrl": "https://open.vhb.org/vhb_logo-OPEN_vhb.jpg",
    "license": {
      "type": "License",
      "identifier": "Proprietary"
    }
  },
  "trailer": {
    "type": "VideoObject",
    "contentUrl": "https://youtu.be/aXwOK_fJ8cI",
    "license": {
      "type": "License",
      "identifier": "Proprietary"
    }
  },
  "license": {
    "type": "License",
    "identifier": "All rights reserved",
    "id": "https://en.wikipedia.org/wiki/All_rights_reserved"
  },
  "publisher": {
    "id": "https://open.vhb.org",
    "type": "Organization",
    "name": {
      "de": "OPEN vhb"
    },
    "sameAs": ["https://open.vhb.org"],
    "image": {
      "type": "ImageObject",
      "contentUrl": "https://open.vhb.org/vhb_logo-OPEN_vhb.jpg",
      "description": {
        "de": "The OPEN vhb logo"
      },
      "license": {
        "type": "License",
        "identifier": "Proprietary"
      }
    }
  },
  "creator": [
    {
      "id": "https://open.vhb.org",
      "type": "Organization",
      "name": {
        "de": "OPEN vhb"
      }
    }
  ],
  "isAccessibleForFree": true
}
