=== MOOChub/schema/draft/schemas/course.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://w3id.org/moochub/draft/schemas/course.json",
  "title": "MOOChub v4 learning opportunity",
  "description": "A MOOChub v4 course profile for a learning resource offered by a provider.",
  "type": "object",
  "properties": {
    "@context": {
      "$ref": "https://w3id.org/moochub/draft/schemas/context-schema.json"
    },
    "type": {
      "$ref": "https://w3id.org/moochub/draft/schemas/courseType.json"
    },
    "id": {
      "$ref": "https://w3id.org/moochub/draft/schemas/id.json"
    },
    "url": {
      "$ref": "https://w3id.org/moochub/draft/schemas/url.json"
    },
    "name": {
      "$ref": "https://w3id.org/kim/amb/20231019/schemas/localizedString.json"
    },
    "publisher": {
      "$ref": "https://w3id.org/moochub/draft/schemas/publisher.json"
    },
    "creator": {
      "$ref": "https://w3id.org/moochub/draft/schemas/creator.json"
    },
    "license": {
      "$ref": "https://w3id.org/moochub/draft/schemas/license.json"
    },
    "courseCode": {
      "$ref": "https://w3id.org/moochub/draft/schemas/courseCode.json"
    },
    "abstract": {
      "$ref": "https://w3id.org/kim/amb/20231019/schemas/localizedString.json"
    },
    "description": {
      "$ref": "https://w3id.org/moochub/draft/schemas/richText.json"
    },
    "keywords": {
      "$ref": "https://w3id.org/kim/amb/20231019/schemas/keywords.json"
    },
    "inLanguage": {
      "$ref": "https://w3id.org/kim/amb/20231019/schemas/inLanguage.json"
    },
    "timeRequired": {
      "$ref": "https://w3id.org/moochub/draft/schemas/timeRequired.json"
    },
    "numberOfCredits": {
      "$ref": "https://w3id.org/moochub/draft/schemas/numberOfCredits.json"
    },
    "interactivityType": {
      "$ref": "https://w3id.org/kim/amb/20231019/schemas/interactivityType.json"
    },
    "isAccessibleForFree": {
      "$ref": "https://w3id.org/kim/amb/20231019/schemas/isAccessibleForFree.json"
    },
    "conditionsOfAccess": {
      "$ref": "https://w3id.org/kim/amb/20231019/schemas/conditionsOfAccess.json"
    },
    "accessMode": {
      "$ref": "https://w3id.org/moochub/draft/schemas/accessMode.json"
    },
    "image": {
      "$ref": "https://w3id.org/moochub/draft/schemas/image.json"
    },
    "trailer": {
      "$ref": "https://w3id.org/moochub/draft/schemas/trailer.json"
    },
    "contributor": {
      "$ref": "https://w3id.org/moochub/draft/schemas/contributor.json"
    },
    "funder": {
      "$ref": "https://w3id.org/moochub/draft/schemas/funder.json"
    },
    "audience": {
      "$ref": "https://w3id.org/moochub/draft/schemas/audience.json"
    },
    "coursePrerequisites": {
      "$ref": "https://w3id.org/moochub/draft/schemas/richText.json"
    },
    "prerequisiteCourses": {
      "$ref": "https://w3id.org/moochub/draft/schemas/prerequisiteCourses.json"
    },
    "competencyRequired": {
      "$ref": "https://w3id.org/moochub/draft/schemas/competencyRequired.json"
    },
    "learningOutcomeSummary": {
      "$ref": "https://w3id.org/moochub/draft/schemas/richText.json"
    },
    "teaches": {
      "$ref": "https://w3id.org/moochub/draft/schemas/teaches.json"
    },
    "assesses": {
      "$ref": "https://w3id.org/moochub/draft/schemas/assesses.json"
    },
    "educationalLevel": {
      "$ref": "https://w3id.org/moochub/draft/schemas/educationalLevels.json"
    },
    "educationalAlignment": {
      "$ref": "https://w3id.org/moochub/draft/schemas/educationalAlignment.json"
    },
    "hasCourseInstance": {
      "$ref": "https://w3id.org/moochub/draft/schemas/hasCourseInstance.json"
    },
    "educationalCredentialAwarded": {
      "$ref": "https://w3id.org/moochub/draft/schemas/educationalCredentialAwarded.json"
    },
    "isBasedOn": {
      "$ref": "https://w3id.org/moochub/draft/schemas/isBasedOn.json"
    },
    "isPartOf": {
      "$ref": "https://w3id.org/moochub/draft/schemas/isPartOf.json"
    },
    "hasPart": {
      "$ref": "https://w3id.org/moochub/draft/schemas/hasPart.json"
    },
    "aggregateRating": {
      "$ref": "https://w3id.org/moochub/draft/schemas/aggregateRating.json"
    },
    "dateCreated": {
      "type": "string",
      "format": "date-time"
    },
    "datePublished": {
      "type": "string",
      "format": "date-time"
    },
    "dateModified": {
      "type": "string",
      "format": "date-time"
    },
    "expires": {
      "type": "string",
      "format": "date-time"
    }
  },
  "required": ["id", "type", "name", "publisher", "creator", "license"]
}

=== MOOChub/schema/4.0.0/examples/course/valid/richTextCourse.json
{
  "@context": [
    "https://w3id.org/moochub/4.0.0/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "id": "urn:uuid:8c2b5e73-4e90-4ef2-8efb-1ad4c4d46f6b",
  "url": "https://example.org/courses/rich-text",
  "name": {
    "de": "Rich-Text-Kurs"
  },
  "description": [
    {
      "type": "TextObject",
      "inLanguage": "de",
      "text": "## Inhalte\n\nDieser Kurs enthält **formatierte** Inhalte.",
      "encodingFormat": "text/markdown"
    }
  ],
  "type": ["LearningResource", "Course"],
  "publisher": {
    "id": "https://example.org/organizations/example-provider",
    "name": {
      "de": "Beispielanbieter"
    },
    "type": "Organization"
  },
  "creator": [
    {
      "id": "https://example.org/people/beispielperson",
      "type": "Person",
      "name": "Beispielperson"
    }
  ],
  "license": {
    "type": "License",
    "id": "https://spdx.org/licenses/CC-BY-4.0.html",
    "identifier": "CC-BY-4.0"
  }
}

=== MOOChub/schema/4.0.0/examples/course/valid/futurelearnlabCourse.json
{
  "@context": [
    "https://w3id.org/moochub/4.0.0/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "type": ["LearningResource", "Course"],
  "id": "urn:uuid:25616c90-ff84-43cc-9198-e20b3e569d8a",
  "url": "https://futurelearnlab.de/hub/blocks/ildmetaselect/detailpage.php?id=444",
  "name": {
    "de": "Digitalisierung mit Struktur: Der Diamant-Prozess"
  },
  "description": [
    {
      "type": "TextObject",
      "inLanguage": "de",
      "text": "\u003Cdiv class='teasertext'\u003E\u003Cspan class=\"multilang\" lang=\"DE\"\u003EIn diesem Kurs lernen Sie, wie Sie in Ihrem Unternehmen digitale Transformationsprozesse planen und umsetzen können, indem Sie konkrete Digitalisierungsbedarfe in Ihrem Unternehmen identifizieren und adressieren.\u003C/span\u003E\r\n\u003Cbr\u003E\r\n\u003Cbr\u003E\r\n\u003Cspan class=\"multilang\" lang=\"EN\"\u003EIn this course, you will learn how to plan and implement digital transformation processes in your company by identifying and addressing specific digitalization needs in your company.\u003Cbr\u003E\u003C/span\u003E\r\n\u003Cbr\u003E\r\n\u003Cbr\u003E\r\n\u003Ch4\u003E\u003Cspan class=\"multilang\" lang=\"DE\"\u003E\u003Cstrong\u003E\r\n            Die Autor*Innen\r\n        \u003C/strong\u003E\u003C/span\u003E\u003C/h4\u003E\r\n\u003Ch5\u003E\u003C/h5\u003E\u003Cspan class=\"multilang\" lang=\"DE\"\u003E\u003Cstrong\u003EHenrik Welp\u003C/strong\u003E Ist Digitalberater beim European-Digital-Innovation Hub Schleswig-Holstein. In dieser Rolle unterstützt er kleine und mittlere Unternehmen, Organisationen der öffentlichen Verwaltung und Startups bei der Umsetzung ihrer Digitalisierungsvorhaben mit verschiedenen Workshop-Angeboten und wirkt so aktiv an de Gestaltung neuer digitaler Infrastrukturen mit. \u003Cbr\u003E\u003Cbr\u003E\u003Cstrong\u003EAnna Lena Möller\u003C/strong\u003E Ist Instructional Designerin am Institut für Interaktive Systeme der Technischen Hochschule Lübeck. Im Kontext des European Digital Innovation Hub entwickelt und beforscht Sie innovative Lehr-Lern-Angebote. Ihre Schwerpunkte liegen in Lernszenarien die abseits des klassischen Schreibtisch-Kontextes funktionieren (Microlearning) und in der Erforschung von Transferstrategien in digitalen Lernprozessen.\r\n    \u003Cbr\u003E\u003C/span\u003E\r\n\u003Cbr\u003E\r\n\u003Cbr\u003E\r\n\u003Ch4\u003E\u003Cspan class=\"multilang\" lang=\"EN\"\u003EThe authors \u003C/span\u003E\u003C/h4\u003E\u003Cspan class=\"multilang\" lang=\"EN\"\u003E\u003Cstrong\u003EHenrik Welp\u003C/strong\u003E&nbsp;is digital consultant in the project European Digital Innovation Hub Schleswig-Holstein. In this role, he supports small and medium-sized enterprises, public administration organizations and start-ups in the implementation of their digitisation projects with various workshop offers and thus actively participates in the design of new digital infrastructures. \u003Cbr\u003E\u003Cbr\u003E\u003Cstrong\u003EAnna Lena Möller\u003C/strong\u003E&nbsp;is an instructional designer at the Institute for Interactive Systems at Lübeck University of Applied Sciences. In the context of the European Digital Innovation Hub Schleswig-Holstein, she develops and researches innovative teaching and learning designs. Her focus are learning scenarios that work outside the classic office context (microlearning) and on researching transfer strategies in digital learning processes.\r\n\u003C/span\u003E\u003C/div\u003E\u003Cdiv class='learninggoals'\u003E\u003Ch3\u003ELernziele\u003C/h3\u003E\u003Cspan class=\"multilang\" lang=\"DE\"\u003EZiel dieses Lernangebotes ist es Sie zu befähigen, die für Ihr Unternehmen kritischen Digitalisierungsbedarfe mithilfe des Diamant-Prozesses strukturiert angehen und Lösungsansätze hierfür entwickeln zu können.\u003C/span\u003E\r\n\u003Cbr\u003E\r\n\u003Cbr\u003E\r\n\u003Cspan class=\"multilang\" lang=\"EN\"\u003EThe aim of this course is&nbsp; to enable you to address the critical digitalization needs of your company in a structured way using the Diamond Process and to develop solutions for them.\u003C/span\u003E\u003C/div\u003E",
      "encodingFormat": "text/html"
    }
  ],
  "inLanguage": ["de"],
  "isAccessibleForFree": true,
  "hasCourseInstance": [
    {
      "id": "urn:uuid:bf3307cf-d5de-4256-8f07-f91ece671a9e",
      "type": "CourseInstance",
      "courseMode": ["online", "asynchronous"],
      "duration": "PT2H"
    }
  ],
  "teaches": [
    {
      "type": "Competency",
      "id": "urn:uuid:4364929a-2844-46d0-837f-626f8998fa95",
      "name": {
        "de": "Digitale Transformation in Unternehmen planen und umsetzen"
      },
      "relatedSkill": [
        {
          "type": "Concept",
          "id": "http://data.europa.eu/esco/skill/0458f6a0-cb54-4ff5-a543-b2c5354e17c0",
          "inScheme": "http://data.europa.eu/esco/concept-scheme/skills",
          "prefLabel": {
            "de": "beim digitalen Wandel industrieller Prozesse auf dem neuesten Stand sein",
            "en": "keep up with digital transformation of industrial processes"
          }
        },
        {
          "type": "Concept",
          "id": "http://data.europa.eu/esco/skill/553ad092-b799-44c9-a94c-65a84fdc7526",
          "inScheme": "http://data.europa.eu/esco/concept-scheme/skills",
          "prefLabel": {
            "de": "Verfahren für innerbetrieblichen Strukturwandel ermitteln",
            "en": "identify processes for re-engineering"
          }
        },
        {
          "type": "Concept",
          "id": "http://data.europa.eu/esco/skill/f5308e60-d763-4ead-be95-88c96fb3e02b",
          "inScheme": "http://data.europa.eu/esco/concept-scheme/skills",
          "prefLabel": {
            "de": "beim digitalen Wandel industrieller Prozesse auf dem neuesten Stand sein",
            "en": "sich an Veränderungen in Technologieentwicklungsplänen anpassen"
          }
        }
      ],
      "proficiencyLevel": [
        {
          "type": "Concept",
          "id": "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/DIGCOMP/DIGCOMP3.0/DigComp%203.0%20Data%20Supplement%2024%20Nov%202025.jsonld#ProficiencyLevel/Basic_2",
          "inScheme": "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/DIGCOMP/DIGCOMP3.0/DigComp%203.0%20Data%20Supplement%2024%20Nov%202025.jsonld",
          "prefLabel": {
            "en": "Grundlagen (Level 2)"
          }
        }
      ]
    }
  ],
  "publisher": {
    "id": "https://www.th-luebeck.de",
    "type": "Organization",
    "name": {
      "de": "Technische Hochschule Lübeck"
    },
    "sameAs": ["https://www.th-luebeck.de"],
    "image": {
      "type": "ImageObject",
      "contentUrl": "https://futurelearnlab.de/hub/pluginfile.php/1/local_ildmeta/provider/2/fhl-intern-logo.png",
      "license": {
        "type": "License",
        "identifier": "Proprietary"
      }
    }
  },
  "contributor": [
    {
      "id": "https://www.th-luebeck.de/isy",
      "type": "Organization",
      "name": {
        "de": "Institut für Interaktive Systeme"
      },
      "sameAs": ["https://www.th-luebeck.de/isy"]
    }
  ],
  "creator": [
    {
      "id": "https://www.th-luebeck.de",
      "type": "Organization",
      "name": {
        "de": "Technische Hochschule Lübeck"
      }
    }
  ],
  "image": {
    "type": "ImageObject",
    "contentUrl": "https://futurelearnlab.de/hub/pluginfile.php/47429/course/overviewfiles/Kursgrafik_100x100.png",
    "license": {
      "type": "License",
      "identifier": "Proprietary"
    }
  },
  "license": {
    "type": "License",
    "identifier": "CC-BY-NC-SA-4.0",
    "id": "https://spdx.org/licenses/CC-BY-NC-SA-4.0.html"
  },
  "expires": "2025-06-17T00:00:00+02:00"
}

=== MOOChub/schema/4.0.0/examples/course/valid/egovcampusCourse.json
{
  "@context": [
    "https://w3id.org/moochub/4.0.0/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "type": ["LearningResource", "Course"],
  "id": "urn:uuid:90c77c77-affd-5dcc-954d-760edf02b890",
  "url": "https://moodle.egov-campus.org/course/view.php?id=1",
  "name": {
    "de": "eGov-Campus"
  },
  "description": [
    {
      "type": "TextObject",
      "inLanguage": "de",
      "text": "\u003Cp\u003EDer eGov-Campus, die Lernplattform für E-Government\u003C/p\u003E",
      "encodingFormat": "text/html"
    }
  ],
  "isAccessibleForFree": true,
  "creator": [
    {
      "id": "https://egov-campus.org/",
      "type": "Organization",
      "name": {
        "de": "eGov-Campus"
      }
    }
  ],
  "publisher": {
    "id": "https://egov-campus.org/",
    "type": "Organization",
    "name": {
      "de": "eGov-Campus"
    },
    "sameAs": ["https://egov-campus.org/"]
  },
  "license": {
    "type": "License",
    "identifier": "proprietary"
  },
  "aggregateRating": {
    "ratingValue": 0,
    "ratingCount": 0,
    "bestRating": 5,
    "worstRating": 1
  }
}

=== MOOChub/schema/draft/examples/course/valid/kicampusCourse.json
{
  "@context": [
    "https://w3id.org/moochub/draft/context.jsonld",
    {
      "@language": "en"
    }
  ],
  "type": ["LearningResource", "Course"],
  "id": "urn:uuid:bb1761a4-8019-5371-bd32-b45ace07f6b1",
  "url": "https://moodle.ki-campus.org/course/view.php?id=6",
  "name": {
    "en": "Introduction to Machine Learning Part 1: Foundations"
  },
  "description": [
    {
      "type": "TextObject",
      "inLanguage": "en",
      "text": "\u003Ch5\u003E\u003Cspan style=\"\"\u003E\u003Cspan class=\"\" style=\"font-weight: normal; color: rgb(0, 0, 0);\"\u003E\r\n\u003Cp\u003E\u003Cstrong\u003EMachine Learning (ML)&nbsp;\u003C/strong\u003Eis at the core of many applications of \u003Cstrong\u003Eartificial intelligence\u003C/strong\u003E. A key goal of this course series is to teach the \u003Cstrong\u003Efundamental building blocks \u003C/strong\u003Ebehind\u003Cstrong\u003E supervised ML\u003C/strong\u003E. Additional to \u003Cstrong\u003Eunderstanding\u003C/strong\u003E the theoretical basics, participants will learn how to \u003Cstrong\u003Eapply\u003C/strong\u003E and evaluate different ML algorithms in \u003Cstrong\u003ER and Python \u003C/strong\u003Ewith a focus on tabular data.\u003C/p\u003E\r\n\u003Cp\u003EAfter a general \u003Cstrong\u003Eintroduction to the basics of ML\u003C/strong\u003E in part 1/3, participants will get in touch with several \u003Cstrong\u003Elearning algorithms\u003C/strong\u003E&nbsp;in part 2/3. Finally, we will cover the \u003Cstrong\u003Eevaluation and tuning of ML models\u003C/strong\u003E in depth in part 3/3.\u003C/p\u003E\u003C/span\u003E\u003C/span\u003E\u003C/h5\u003E",
      "encodingFormat": "text/html"
    }
  ],
  "isAccessibleForFree": true,
  "creator": [
    {
      "id": "https://ki-campus.org/",
      "type": "Organization",
      "name": {
        "en": "KI Campus"
      }
    }
  ],
  "publisher": {
    "id": "https://ki-campus.org/",
    "type": "Organization",
    "name": {
      "en": "KI Campus"
    },
    "sameAs": ["https://ki-campus.org/"]
  },
  "license": {
    "type": "License",
    "identifier": "proprietary"
  },
  "aggregateRating": {
    "ratingValue": 4.67,
    "ratingCount": 3,
    "bestRating": 5,
    "worstRating": 1
  }
}

=== MOOChub/schema/4.0.0/examples/course/valid/learningOutcome.json
{
  "@context": [
    "https://w3id.org/moochub/4.0.0/context.jsonld",
    {
      "@language": "de"
    }
  ],
  "id": "urn:uuid:c96a2376-bdf2-4307-a21f-19a4ff141b5f",
  "url": "https://futurelearnlab.de/detailpage.php?id=18",
  "name": {
    "de": "Digital Trainer (Gesamtkurs)"
  },
  "type": ["LearningResource", "Course"],
  "publisher": {
    "id": "https://example.org/organizations/isy",
    "name": {
      "de": "Institut für Interaktive Systeme"
    },
    "type": "Organization"
  },
  "creator": [
    {
      "id": "https://example.org/people/beispielperson",
      "type": "Person",
      "name": "Beispielperson"
    }
  ],
  "license": {
    "type": "License",
    "identifier": "Propriatary"
  },
  "teaches": [
    {
      "id": "urn:uuid:9e7c1b64-c460-4672-b666-cb64dc2d3921",
      "type": "Competency",
      "name": {
        "en": "Communication, collaboration and creativity"
      },
      "relatedSkill": [
        {
          "id": "http://data.europa.eu/esco/skill/326809fc-238d-40c2-881e-40042f7f2f0d",
          "type": "Concept",
          "inScheme": "http://data.europa.eu/esco/concept-scheme/skills",
          "prefLabel": {
            "en": "establish collaborative relations"
          }
        },
        {
          "id": "http://data.europa.eu/esco/skill/80f308e6-0e09-404a-80cd-ec5f50f6f304",
          "type": "Concept",
          "inScheme": "http://data.europa.eu/esco/concept-scheme/skills",
          "prefLabel": {
            "en": "communicate with target community"
          }
        },
        {
          "id": "http://data.europa.eu/esco/skill/ccdf3597-5c80-410f-896d-e1bdfa223de9",
          "type": "Concept",
          "inScheme": "http://data.europa.eu/esco/concept-scheme/skills",
          "prefLabel": {
            "en": "stimulate creativity in the team"
          }
        }
      ]
    },
    {
      "id": "urn:uuid:3f9f5899-c3cd-43a9-aecb-266483fcbf6a",
      "type": "Competency",
      "name": {
        "en": "Developing digital content"
      },
      "relatedSkill": [
        {
          "id": "http://data.europa.eu/esco/skill/5fd5c985-eaaa-47aa-8314-62359c54505a",
          "type": "Concept",
          "inScheme": "http://data.europa.eu/esco/concept-scheme/skills",
          "prefLabel": {
            "en": "develop digital content"
          }
        },
        {
          "id": "http://data.europa.eu/snb/dcf/u69o196gu6",
          "type": "Concept",
          "inScheme": "http://data.europa.eu/snb/dcf/25831c2",
          "prefLabel": {
            "en": "Developing digital content"
          }
        },
        {
          "id": "http://data.europa.eu/snb/dcf/3ol5wi3605",
          "type": "Concept",
          "inScheme": "http://data.europa.eu/snb/dcf/25831c2",
          "prefLabel": {
            "en": "Developing digital content Level 4"
          }
        }
      ]
    }
  ],
  "learningOutcomeSummary": [
    {
      "type": "TextObject",
      "inLanguage": "en",
      "text": "Stduents will be able to communicate, collaborate and stimulate creativity in the team. They will also be able to develop digital content.",
      "encodingFormat": "text/plain"
    }
  ],
  "coursePrerequisites": [
    {
      "type": "TextObject",
      "inLanguage": "en",
      "text": "Basic digital literacy and familiarity with online learning platforms and English B2 level.",
      "encodingFormat": "text/plain"
    }
  ],
  "prerequisiteCourses": [
    {
      "id": "urn:uuid:1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p",
      "type": ["LearningResource", "Course"],
      "name": {
        "en": "Introduction to Digital Skills"
      }
    }
  ],
  "competencyRequired": [
    {
      "id": "urn:uuid:7e8f9g0h-1i2j-3k4l-5m6n-7o8p9q0r1s2t",
      "type": "Competency",
      "name": {
        "en": "Englisch B2"
      },
      "relatedSkill": [
        {
          "id": "http://data.europa.eu/esco/skill/7ee20fe2-facd-4cc5-837b-927429e0e7ac",
          "type": "Concept",
          "inScheme": "http://data.europa.eu/esco/concept-scheme/skills",
          "prefLabel": {
            "en": "understand written English"
          }
        }
      ]
    }
  ]
}
